### ISSUE TITLE
inner_keys_klen has be greater than 2

### ISSUE THREAD

**Issue by honeyAcorn** [iopsystems/rpc-perf#341]
inner_keys_klen = 1 or 2 will cause the whole load test to stop running.

### Expected behavior

I tried to run sort_set load test.
If I set the `inner_keys_klen = 1`
and `inner_keys_nkeys = 100_000`
The whole load test stopped running.

But if I set the `inner_keys_klen = 3`
and `inner_keys_nkeys = 100_000`
The load test runs normally.

### Steps to reproduce the behavior

`./stop.sh`
`vim /opt/momento/config.toml` => and add the following part
`./start.sh <test to run>`

Then you will see it not running.

```toml
[workload.ratelimit]
# ramp up the workload in steps
start = 100_000

# An example keyspace showcasing the use of the `sorted set` family of commands.
#
# Note that we use the inner key generator to produce `elements` for these
# operations. The values are `f64` so we do not need to specify parameters for
# the value generator.
[[workload.keyspace]]
# sets the relative weight of this keyspace: defaults to 1
weight = 1
# sets the length of the key, in bytes
klen = 16
# sets the number of keys that will be generated
nkeys = 1
# sets the length of the inner key, in bytesp
inner_keys_klen = 1
# sets the number of inner keys that will be generated
inner_keys_nkeys = 100_000
# controls what commands will be used in this keyspace
commands = [
    # adds an element to a sorted set
    { verb = "sorted_set_put", weight = 1 },

    # get the score for an element in a sorted set
    { verb = "sorted_set_get_score", weight = 4 },
]
```
